### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by argoroots** [poying/node-zoom#6]
On npm install node-zoom I get following error:
```
> node-zoom@0.1.1 install /data/node_modules/node-zoom
> node-gyp rebuild


/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --cflags gnutls' returned exit status 127. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/node_modules/node-zoom
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-zoom"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! node-zoom@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-zoom@0.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-zoom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-zoom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/npm-debug.log
```

**Comment by poying** [comment]
`pkg-config` is not found, so you have to install it:

```bash
# homebrew (mac)
$ brew install pkg-config
# ubuntu
$ sudo apt-get install pkg-config
```

**Comment by argoroots** [comment]
Thanks!

I also missed packages libxslt-dev, dpkg-dev and python. Maybe its good to put those into README.md
