### ISSUE TITLE
Error: Query not found

### ISSUE THREAD

**Issue by argoroots** [poying/node-zoom#7]
What I'm doing wrong here?

```javascript
var zoom = require('node-zoom')
var books = zoom.connection('192.83.186.170:210/INNOPAC')
books.set('preferredRecordSyntax', 'usmarc')
books.query('@attr 1=4 台灣')
books.createReadStream()
books.on('data', function (record) {
    console.log(record.json)
})
```

```
> var zoom = require('node-zoom')
undefined
> var books = zoom.connection('192.83.186.170:210/INNOPAC')
undefined
> books.set('preferredRecordSyntax', 'usmarc')
{ _connected: false,
  _options: {},
  _conn: {},
  _host: '192.83.186.170',
  _port: 210 }
> books.query('@attr 1=4 台灣')
{ _query: {} }
> books.createReadStream()
Error: Query not found
    at Connection.conn.createReadStream (/node_modules/node-zoom/lib/connection.js:81:11)
    at repl:1:7
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
> books.on('data', function (record) {
...     console.log(record.json)
... })
TypeError: undefined is not a function
    at repl:1:7
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
> 
```

**Comment by argoroots** [comment]
Actual server and code what I use is

```javascript
var books = zoom.connection('193.40.4.242:212/INNOPAC')
books.set('preferredRecordSyntax', 'usmarc')
books.query('pqf', '@attr 1=4 hobbit')
books.createReadStream()
books.on('data', function (record) {
    console.log(record.json)
})
```

But result is same - Error: Query not found

**Comment by argoroots** [comment]
Never mind! Got it working in production server.
